base_url = "https://about.nokotaro.com"
compile_sass = true
title = "Nokotaro.com"
description = "A clean resume theme"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Nokotaro"
last_name = "Takeda"
address = "Saitama, Japan"
email = "takenoko@mail.nokotaro.com"
favicon = "/favicon.ico"
avatar = "/media/avatar.png"

katex = false
show_about = true
show_skills = true
show_projects = true
show_opensource = true
show_publications = true
show_experience = true
show_education = true
show_blog = true
